### ISSUE TITLE
Refactor SERP view code for consistency

### ISSUE THREAD

**Issue by nickmarden** [GSA/search-gov#35]
We've completed a number of stories recently to add missing sections to various SERP layouts. Our view code is unnecessarily scattered and inconsistent. This story is intended to do two things:
1) identify the sections/modules that should appear on all SERPs (index, i14y, docs, blended)
2) consolidate those sections into shared partials, so that the layouts will be consistent

SERP sections:
- SERP alerts
- spelling suggestion
- matching_site_limits 
- best bets
- medical topics
- jobs
- tweets
- video news items (recent)
- news items (recent)

if search results are present: (Note: we might reconsider this logic. Why only show the following data if there *are* search results?)
- results
- offer_other_web_results
- federal register docs
- news items (older than 5 days, less than 4 months)
- related searches
- pagination

This story needs some fleshing out upon review of the various SERPs.

**Comment by MothOnMars** [comment]
@nickmarden , I'm going to close this one up. Step 1, "identify the sections/modules that should appear on all SERPs", will require reviewing the existing SERP code, identifying consistent and inconsistent elements, and discussing the expected behavior for each SERP with someone on the product side. The amount of discussion and discovery plus the brittle nature of our SERP code in general would make this a mine field for an external resource.
